grader_app/code_grader/routes.py
from flask import Blueprint, render_template, current_app

code_bp = Blueprint(
    'code', __name__, 
    template_folder='templates', 
    static_folder='static',
    url_prefix='/code'
)

@code_bp.route('/')
def index():
    sorted_dirlist = current_app.config['CODE_LIST']
    finished = [False for report in sorted_dirlist]
    return render_template("dirlist.html", dirlist=sorted_dirlist, finished=finished)

grader_app/main/routes.py
from flask import Blueprint, render_template, current_app
from grader_app.utils import refresh_app_config
from flask import redirect, request, url_for


main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    return render_template("index.html")

@main_bp.route('/reload_reports/')
def reload_reports():
    """PDFとCodeのリストを再読み込みするルート"""
    refresh_app_config()
    return redirect(request.referrer or url_for('main.index'))

grader_app/templates/authorlist.html
{% extends "base.html" %}

{% block title %}提出一覧{% endblock %}

{% block navigation %}
<nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{{ url_for(request.blueprint + '.index') }}">課題一覧</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<h1>{{report}}</h1>
<ul>
    {% for a in author_list %}
    <li>
        <a href="/pdf/{{report_index}}/{{loop.index0}}/0">{{a}}</a>
        <span class="check">
            {%if finished[loop.index0]%}
            <i class="bi bi-check-square-fill"></i>
            {%endif%}
        </span>
    </li>
    {% endfor %}
</ul>
{% endblock %}

grader_app/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    {% block additional_css %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>{% block title %}採点ツール{% endblock %}</title>
</head>

<body>
    <header>
        {% block navigation %}{% endblock %}
    </header>
    <main class="container">
        <div class="row">
            <div class="col-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
    {%block scripts %}{% endblock %}
</body>

</html>

grader_app/templates/dirlist.html
{% extends "base.html" %}

{% block title %}課題一覧{% endblock %}

{% block content %}
<h1>課題一覧</h1>
<ul>
    {% for d in dirlist %}
    <li><a href="./{{loop.index0}}/students/">{{d}}</a>
        {% if finished[loop.index0] %}
        <span class="check">
            <i class="bi bi-check-square-fill"></i>
        </span>
        {% endif %}
        [<a href="/edit_problems/{{loop.index0}}?prevpage='/'">問題編集</a>]
    </li>
    {% endfor %}
</ul>
{% endblock %}

grader_app/templates/edit_problems.html
{% extends "base.html" %}

{% block additional_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/edit_problems.css') }}">
{% endblock %}

{% block title %}問題編集{% endblock %}

{% block navigation %}
        <nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">

                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="{{ url_for(request.blueprint + '.index') }}">課題一覧</a></li>
                        {% if report_index >= 0%}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for(request.blueprint + '.student_list', report_index=report_index) }}">提出一覧</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
{% endblock %}

{% block content %}
                <h1>Problem List</h1>
                <h2>{{report_name}}</h2>

                <ul id="problem-list">
                    {% for q_id in data.order %}
                    <li class="list-item" data-id="{{ q_id }}">
                        <span class="handle">⠿</span>
                        <textarea class="editable problem-text" rows="3">{{ data.problems[q_id] }}</textarea>

                        <div class="summary-container">正答: {{summary.correct[q_id]}}/{{summary.total[q_id]}}({{ "%.1f" | format(summary.correct[q_id] / summary.total[q_id] * 100) }}%)</div>
                        
                        <div class="point-container">
                            <input type="number" class="point-input" 
                                value="{{ data.points[q_id] if data.points else 0 }}" 
                                min="0" step="0.1">
                            <span class="point-unit">点</span>
                        </div>

                        <button class="btn btn-outline-danger del-btn">削除</button>
                    </li>
                    {% endfor %}
                </ul>
                <div id="button-group">
                    <button class="btn btn-outline-primary" id="addBtn">新しい問題を追加</button>
                    <button id="saveBtn" class="btn btn-primary save"
                    data-save-url="{{ url_for(request.blueprint + '.save_problems', report_index=report_index) }}"
                    data-back-url="{{back_url}}">保存</button>

                    <!-- <button id="saveBtn" style="background-color: #28a745; color: white;">保存してファイルに書き込む</button> -->
                    <button class="btn btn-danger" id="cancelBtn" data-back-url="{{ back_url }}">キャンセル</button>
                </div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>
<script src="{{ url_for('static', filename='js/edit_problems.js') }}"></script>
{% endblock %}

grader_app/templates/index.html
{% extends "base.html" %}
{% block title %}採点ツール{% endblock %}

{% block content %}
<ul>
    <li><a href="{{ url_for('pdf.index') }}">PDF採点ツール</a></li>
    <li><a href="{{ url_for('code.index') }}">プログラミング採点ツール</a></li>
</ul>
{% endblock %}

grader_app/templates/reportlist_base.html
{% extends "base.html" %}

{% block title %}課題一覧{% endblock %}

{% block content %}
<h1>課題一覧</h1>
[<a href="{{ url_for('main.reload_reports') }}">リスト再読み込み</a>]
<ul>
    {% for d in dirlist %}
    <li><a href="{{ url_for(request.blueprint + '.student_list', report_index=loop.index0) }}">{{d}}</a>
        <span id="status-{{loop.index0}}" class="status-text text-secondary" data-check-url="{{ url_for(request.blueprint + '.check_all_finished', report_index=loop.index0) }}">
            <i class="bi bi-arrow-repeat spin-icon"></i>
        </span>
        [<a href="{{ url_for(request.blueprint + '.edit_problems', report_index=loop.index0) }}">問題編集</a>]
    </li>
    {% endfor %}
</ul>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/reportlist.js') }}"></script>
{% endblock %}

grader_app/templates/studentlist.html
{% extends "base.html" %}

{% block title %}提出一覧{% endblock %}

{% block navigation %}
<nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{{ url_for(request.blueprint + '.index') }}">課題一覧</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<h1>{{report}}</h1>
<ul id="student-list" data-check-url="{{url_for(request.blueprint + '.check_finished', report_index=report_index)}}">
    {% for a in student_list %}
    <li>
        <a href="{{ url_for(request.blueprint + '.viewer', report_index=report_index, student_index=loop.index0) }}">{{a}}</a>
        <span id="status-{{loop.index0}}" class="status-text text-secondary">
            <i class="bi bi-arrow-repeat spin-icon"></i>
        </span>
    </li>
    {% endfor %}
</ul>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/studentlist.js') }}"></script>
{% endblock %}

grader_app/templates/viewer_base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    {% block additional_css %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <title>{% block title %}PDF Viewer{% endblock %}</title>
</head>

<body>

    <header>
{% block navigation %}
        <nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
            
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="{{ url_for(request.blueprint + '.index') }}">課題一覧</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for(request.blueprint + '.student_list', report_index=report_index) }}">提出一覧</a></li>
                        <li class="nav-item">
                            <a class="nav-link {% if student_index == 0 %}disabled{% endif %}" id="prev-report-link"
                               href="{% if student_index > 0 %}{{ url_for(request.blueprint + '.viewer', student_index=student_index-1, report_index=report_index) }}{% else %}#{% endif %}">
                               前のレポート
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if student_index >= total_students - 1 %}disabled{% endif %}" id="next-report-link"
                               href="{% if student_index < total_students - 1 %}{{ url_for(request.blueprint + '.viewer', student_index=student_index+1, report_index=report_index) }}{% else %}#{% endif %}">
                               次のレポート
                            </a>
                        </li>
                        <li class="nav-item">
                            {% if next_unfinished_index is not none %}
                            <a class="nav-link" id="next-unfinished-report-link"
                               href="{{ url_for(request.blueprint + '.viewer', student_index=next_unfinished_index, report_index=report_index) }}">
                               次の未完了レポート
                            </a>
                            {% else %}
                            <a class="nav-link" id="next-unfinished-report-link"
                               href="{{ url_for(request.blueprint + '.student_list', report_index=report_index) }}">
                               次の未完了レポート
                            </a>
                            {% endif %} 
                        </li>
                    </ul>
                    </div>
                </div>
        </nav>
{% endblock %}
    </header>
    <main class="container">
        <div class="row">
            <div class="col-8">
                {%block maincontent %}{% endblock %}
            </div>
            <div class="col-4 sticky-sidebar">
{%block sidecontent_basic %}
                <div class="form-check">
                    <input type="checkbox" id="setting-auto-transition" class="form-check-input pref-storage">
                    <label class="form-check-label" for="setting-auto-transition">自動ページ遷移</label>
                </div>
                <div class="form-check">
                    <input type="checkbox" id="setting-confirm-required" class="form-check-input pref-storage">
                    <label class="form-check-label" for="setting-confirm-required">遷移時に確認ダイアログを表示</label>
                </div>
                <h2>{{report_name}}</h2>
                <p>{{student_index+1}}/{{total_students}}</p>
                <h3>{{student_name}}</h3>
{% endblock %}
{%block sidecontent %}
                <div class="problems">
                    <form id="problems-form" data-save-url="{{ url_for(request.blueprint + '.save_grades', report_index=report_index, student_index=student_index) }}">
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>◯</th>
                                <th>△</th>
                                <th>✕</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
{% for q_id in problems.order %}
    {% set problem_text = problems.problems[q_id] %}
    <tr>
        <td>{{ problem_text }}</td>
        <td>
            <input class="form-check-input" type="radio" 
                   name="grade_{{ q_id }}" value="circle" 
                   {% if gardes['grade_' + q_id] == 'circle' %}checked{% endif %}>
        </td>
        <td>
            <input class="form-check-input" type="radio" 
                   name="grade_{{ q_id }}" value="triangle" 
                   {% if gardes['grade_' + q_id] == 'triangle' %}checked{% endif %}>
        </td>
        <td>
            <input class="form-check-input" type="radio" 
                   name="grade_{{ q_id }}" value="cross" 
                   {% if gardes['grade_' + q_id] == 'cross' %}checked{% endif %}>
        </td>
        <td><button type="button" class="btn btn-warning clear-btn" data-target="grade_{{ q_id }}">クリア</button></td>
    </tr>
{% endfor %}
                        </tbody>
                    </table>
                    </form>
                </div>
{% endblock %}
{%block sidecontent_extra %}
                <p><a href="{{ url_for(request.blueprint + '.edit_problems', report_index=report_index, back_url=back_url) }}">採点項目編集</a></p>
{% endblock %}
            </div>
        </div>

    </main>
    {%block scripts %}
        <script src="{{ url_for('static', filename='js/viewer.js') }}"></script>
    {% endblock %}

</body>

</html>